import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster"
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ["vietnamese"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies()
  const initialSession = cookiesStore.get('sessionToken')?.value;
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <Header />
          <AppProvider initialSession={initialSession as string}>
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
