import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import localFont from "next/font/local"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  subsets: ["vietnamese"],
})

// const myFont = localFont({
//   src: [{
//     path: "./Roboto/Roboto-Thin.ttf",
//     weight: "100"
//   },
//   {
//     path: "./Roboto/Roboto-Light.ttf",
//     weight: "300"
//   },
//   {
//     path: "./Roboto/Roboto-Medium.ttf",
//     weight: "500"
//   },
//   {
//     path: "./Roboto/Roboto-Bold.ttf",
//     weight: "700"
//   }
//   ],
//   display: "swap",
//   variable: "--font-roboto"
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
